sudo: false
language: node_js
node_js:
- node
cache: yarn
before_install:
- node --version
- yarn --version
install:
- yarn
script:
- yarn run build
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: $FIREBASE_TOKEN_NEW
