[[members]]
name = "今村 拓道"

[[members]]
name = "大塚 将真"

[[members]]
name = "大坪 翔一"

[[members]]
name = "金森 涼介"

[[members]]
name = "白井 涼"

[[members]]
name = "薗部 優大"

[[members]]
name = "蜂須賀 真一"

[[members]]
name = "山上 大貴"

[[members]]
name = "山崎 史"

