[[members]]
name = "糸田川 大我"
picture = "itotagawa.jpg"
description = "茶番の天才。新作のマリオに出てくるスーパーアイテムを使えば先輩たちなんか余裕ですよ"
team = "ライムライト"

[[members]]
name = "小澤 駿弥"
picture = "ozawa.jpg"
description = "朝ごはんのお箸担当（スティックだから）。成長著しい“the イケメンデビラー”。"

[[members]]
name = "古賀 優太"
picture = "koga.jpg"
description = "なんでそんなハイスペックなんだ！君に眠らされたら誰も文句は言えません……。"
team = "オレオ"

[[members]]
name = "田中 篤志"
picture = "tanaka.jpg"
description = "某K君に眠らされ、目が覚めたら…シガーが上手くなっていた！（ら良いのにね ）"
team = "ライムライト"

[[members]]
name = "中田 哲"
picture = ""
description = "そ、そんな…ファイアボールを5つも投げられたらマンマミーア！って言っちゃうよ 。"

[[members]]
name = "西川 将司"
picture = ""
description = "突如現れたニューフェイス！いつ本性を見せるのか楽しみ。"

[[members]]
name = "服部 駿佑"
picture = ""
description = "芸術的センス溢れるクラバー。ゆくゆくは豊田さんや鈴木さんのように6本とか7本とか…！？"
team = "オレオ"
