[[members]]
name = "飯塚 大輔"
picture = ""
description = ""

[[members]]
name = "今谷 実希"
picture = "imatani.jpg"
description = "何の道具がメインなのかもはやわからない。いや、カメラかな。写真撮影の天才です。"

[[members]]
name = "上野 寛樹"
picture = "ueno.jpg"
description = "コミカルな演技に定評がある高身長デビラー。先輩たちをガンガン煽っていきます。"

[[members]]
name = "小松原 裕"
picture = "komatsubara.jpg"
description = "いつも熱心にクラブを投げている姿が好印象。ズッキーニは投げちゃダメだよ！"

[[members]]
name = "清水 翔太"
picture = "shimizu.jpg"
description = "某有名アーティストと名前が丸かぶり！歌は苦手だけどジャグリングなら負けないぞ！"

[[members]]
name = "鈴木 凌太"
picture = "suzuki.jpg"
description = "清潔感溢れる爽やかボーイ。声とリングの軌道がとっても綺麗です。"

[[members]]
name = "砂原 啓人"
picture = "sunahara.jpg"
description = "ポ○モン大好きなイケメン、略してポケメン。次の新歓係はキミに決めた！"

[[members]]
name = "竹花 祥"
picture = "takehana.jpg"
description = "不思議なキャラが皆から大人気。普段は俺様タイプじゃなくて、素直な良い子です。"

