[[members]]
name = "飯塚 大輔"
picture = ""
description = ""

[[members]]
name = "今谷 実希"
picture = ""
description = ""

[[members]]
name = "上野 寛樹"
picture = ""
description = ""

[[members]]
name = "小松原 裕"
picture = ""
description = ""

[[members]]
name = "清水 翔太"
picture = ""
description = "第19代会長"

[[members]]
name = "鈴木 凌太"
picture = ""
description = ""

[[members]]
name = "砂原 啓人"
picture = ""
description = ""

[[members]]
name = "竹花 祥"
picture = ""
description = ""

