[[members]]
name = "石水 泰樹"
picture = "ishimizu_edit.jpg"
description = "圧倒的なディアボロの技術を持っている。
パフォーマンスもトップレベルだ！"

[[members]]
name = "磯部 宏征"
picture = ""
description = ""

[[members]]
name = "稲葉 昂希"
picture = "inaba.jpg"
description = "イケメンデビラー！
あまりのかっこよさに泡吹いて倒れちゃう!?"

[[members]]
name = "河村 綾太"
picture = ""
description = "多芸なピ○チュウ。
インスタで1万いいねを稼ぐらしい。"

[[members]]
name = "小林 悠太"
picture = ""
description = "デビルスティックで一風変わった技をするよ。先輩に抗っていこう。"

[[members]]
name = "酒徳 波和"
picture = ""
description = "リングを操る聖母様。
眩しすぎて目が見えなくなる。"

[[members]]
name = "作田 淳弥"
picture = ""
description = ""

[[members]]
name = "白井 夢月"
picture = ""
description = "元気一杯魔法使い。
道具が不思議な動きをするよ。"

[[members]]
name = "高木 彩花"
picture = ""
description = ""

[[members]]
name = "田中 嵩士"
picture = ""
description = "お調子者かと思いきや意外にしっかりとした一面も…？
成長著しいディアボラー！"

[[members]]
name = "戸板 治紀"
picture = ""
description = "ポイを武器に戦うぞ！
え、剣？やだなぁ、これは、お・しゃ・れ。"

[[members]]
name = "戸塚 大貴"
picture = ""
description = "留学帰りのディアボ…？ボーラー？
コミュ力がExcellentです。"

[[members]]
name = "西村 希望"
picture = ""
description = "デビルスティックが相棒です。
棒だけに………なんてね！"

[[members]]
name = "松巾 拓未"
picture = ""
description = "後輩想いの優しい先輩(になる予定)。
ヨーヨーは大道芸に関係なかった。"

[[members]]
name = "矢矧 春菜"
picture = ""
description = "気まぐれなお姫様。
ルネパフェを献上しよう。"

[[members]]
name = "山崎 琉央"
picture = ""
description = "ポイを操る短パン小僧。(なお写真はシガー)
見た目寒そうだが内には熱い想いを秘めている。"

[[members]]
name = "山下 巧"
picture = ""
description = "ディアボロ上手なへっぽこ魔王様。
演技力が流石としか言えない。"

[[members]]
name = "山下 湧志朗"
picture = ""
description = "インスタ映えを求めて旅をしていた。
クラブの主な用途はマイクです。"

[[members]]
name = "和田 岳"
picture = ""
description = ""

