[[members]]
name = "石水 泰樹"
picture = "ishimizu.jpg"
description = "圧倒的なディアボロの技術を持っている。パフォーマンスもトップレベルだ！"

[[members]]
name = "稲葉 昂希"
picture = "inaba.jpg"
description = "イケメンデビラー！あまりのかっこよさに泡吹いて倒れちゃう!?"

[[members]]
name = "河村 綾太"
picture = "kawamura.jpg"
description = "多芸なピ○チュウ。インスタで1万いいねを稼ぐらしい。"

[[members]]
name = "小林 悠太"
picture = "kobayashi.jpg"
description = "デビルスティックで一風変わった技をするよ。先輩に抗っていこう。"

[[members]]
name = "酒徳 波和"
picture = "sakatoku.jpg"
description = "リングを操る聖母様。眩しすぎて目が見えなくなる。"

[[members]]
name = "白井 夢月"
picture = "shirai.jpg"
description = "元気一杯魔法使い。道具が不思議な動きをするよ。"

[[members]]
name = "田中 嵩士"
picture = "tanaka.jpg"
description = "お調子者かと思いきや意外にしっかりとした一面も…？成長著しいディアボラー！"

[[members]]
name = "戸板 治紀"
picture = "toita.jpg"
description = "ポイを武器に戦うぞ！え、剣？やだなぁ、これは、お・しゃ・れ。"

[[members]]
name = "戸塚 大貴"
picture = "totsuka.jpg"
description = "留学帰りのディアボ…？ボーラー？コミュ力がExcellentです。"

[[members]]
name = "西村 希望"
picture = "nishimura.jpg"
description = "デビルスティックが相棒です。棒だけに………なんてね！"

[[members]]
name = "松巾 拓未"
picture = "matsuhaba.jpg"
description = "後輩想いの優しい先輩(になる予定)。ヨーヨーは大道芸に関係なかった。"

[[members]]
name = "矢矧 春菜"
picture = "yahagi.jpg"
description = "気まぐれなお姫様。ルネパフェを献上しよう。"

[[members]]
name = "山崎 琉央"
picture = "yamazaki.jpg"
description = "ポイを操る短パン小僧。(なお写真はシガー)見た目寒そうだが内には熱い想いを秘めている。"

[[members]]
name = "山下 巧"
picture = "yamashita takumi.jpg"
description = "ディアボロ上手なへっぽこ魔王様。演技力が流石としか言えない。"

[[members]]
name = "山下 湧志朗"
picture = "yamashita yusiro.jpg"
description = "インスタ映えを求めて旅をしていた。クラブの主な用途はマイクです。"

