[[members]]
name = "出井"
picture = ""
description = "元気いっぱいのポイスピナー。イデイ、いっきまーす！"
team = ""

[[members]]
name = "大本"
picture = ""
description = "ボールとシェーカーを使いこなすジャグラー。お洒落な帽子がトレードマーク。"
team = ""

[[members]]
name = "加藤"
picture = ""
description = "世界一の人見知りトスジャグラー。サーカス大好き！"
team = ""

[[members]]
name = "中井"
picture = ""
description = "マイペースなボーラー。治療にミスはつきものです⁉︎"
team = ""

[[members]]
name = "中村"
picture = ""
description = ""
team = ""

[[members]]
name = "藤原"
picture = ""
description = "ちょっと抜けてるけど頼りになるぞ。赤い鉢巻がとっても印象的なシガラー。"
team = ""

[[members]]
name = "本田"
picture = ""
description = "能天気なボーラー。見た目の3倍何も考えてないらしい(本人談)。"
team = ""

[[members]]
name = "松木"
picture = ""
description = "2ディア特訓中のディアボラー。あとで焼肉行こうね！"
team = ""

[[members]]
name = "三角"
picture = ""
description = "個性的な人間が集まるDonutsでも霞まない個性。演技力抜群のルービックキューブ&ディアボロジャグラー。"
team = ""
