[[members]]
name = "青柳"
picture = ""
description = "スケールがでかい大型新入生。いくつものボールを軽々投げる。"
team = ""

[[members]]
name = "池田"
picture = "ikeda.jpg"
description = "デビルスティックくるくる男。メリークリスマス"
team = ""

[[members]]
name = "岩田"
picture = "iwata.jpg"
description = "賢いボーラー。ルネでミール奴隷をしている。"
team = ""

[[members]]
name = "遠藤"
picture = "endo.jpg"
description = "久しぶりに生まれたシェーカーカップジャグラー。　溢れるアイデアを詰め込むその演技にご注目！"
team = ""

[[members]]
name = "尾鍋"
picture = ""
description = "久しぶりに見ると前よりぐっとうまくなってる不思議なボーラー。背中から哀愁を感じるときがある。"
team = ""

[[members]]
name = "清住"
picture = ""
description = "多分ボディスローが好きなボーラー。たまに足でボールを投げる。"
team = ""

[[members]]
name = "河野"
picture = ""
description = "Donutsでほぼ唯一の皿スピナー。足技が映える"
team = ""

[[members]]
name = "佐藤"
picture = "sato.jpg"
description = "バルーンが上手なディアボラー。最近、先輩の金でカニを食べたらしい。"
team = ""

[[members]]
name = "須崎"
picture = ""
description = "気まぐれリンガー・須崎は遅れてやってくる。"
team = ""

[[members]]
name = "角"
picture = "sumi.jpg"
description = "トスの軌道が非常に美しいボーラー。決めポーズがかわいい。"
team = ""

[[members]]
name = "永井"
picture = "nagai.jpg"
description = "リンガー兼エイトリンガー。リングを愛しているから彼女なんて必要ない！というのは全くの嘘。"
team = ""

[[members]]
name = "平田"
picture = ""
description = "丁寧に練習で技術を磨いてきたボーラー。実はシガーもできる。"
team = ""

[[members]]
name = "堀内"
picture = ""
description = "水晶玉《クリスタル》の魔術師《マジシャン》"
team = ""

[[members]]
name = "水野"
picture = ""
description = "一回生なのに同期から先輩と思われるほどの貫禄がある。トスに心を捧げたシガラー。"
team = ""

[[members]]
name = "森本"
picture = ""
description = "ディアボラー。………なのにどうして5ボールできるんですか？"
team = ""

[[members]]
name = "山健"
picture = ""
description = "けん玉で世界を平和にしたいやまけんです。"
team = ""

[[members]]
name = "山田"
picture = "yamada.jpg"
description = "乃木坂が好きなディアボラー。（多分）先輩に推しのディアボラーがいるらしい。"
team = ""
