[[members]]
name = "坂上"
picture = "sakagami.png"
description = "星をこよなく愛する上品なディアボラー。声にリラクゼーション効果がある。"
team = ""

[[members]]
name = "柴田"
picture = "shibata.png"
description = "ピルエットくるくるボーラー。社長出勤レベル99"
team = ""

[[members]]
name = "杉山"
picture = "sugiyama.png"
description = "元野良のカラフルディアボラー。思ってるよりタッパがある。"
team = ""

[[members]]
name = "椿井"
picture = "tsubai.png"
description = "後輩力高めの笑顔がキュートなデビルスティッカー。しかしその本性は....。"
team = ""

[[members]]
name = "土井"
picture = ""
description = "オーバーヘッドが得意なボーラー。夜にカラーコーンを公園で投げてるらしい。"
team = ""

[[members]]
name = "中川"
picture = "nakagawa.png"
description = "貴重な皿回しジャグラー｡サメ映画のサメに憧れている。"
team = ""

[[members]]
name = "藤井"
picture = "fuji.png"
description = "想像を絶する練習量であらゆる道具を操るシガーボックスジャグラー。半年ごとに髪型が大きく変わる。"
team = ""

[[members]]
name = "船岡"
picture = "funaoka.png"
description = "先輩愛の強いポイスピナー。🍩内のイベント運営もそつなくこなしてくれる。"
team = ""

[[members]]
name = "堀部"
picture = ""
description = "縦にディアボロを回すダイナミックなディアボラー。演技の激しさとは裏腹に繊細な建築模型に苦しんでいる。"
team = ""

