[[members]]
name = "稲葉"
picture = "inaba.jpg"
description = "多才でクリエイティブな、かずはこ系シガラー。おみそ汁が好き。"
team = ""

[[members]]
name = "岩見"
picture = ""
description = "勝負事が大好きなリンガー。方向違いの真面目さのせいで不真面目に見える。好きな言葉はラブ&ピース。"
team = ""

[[members]]
name = "岡本"
picture = ""
description = "ボールとクラブを自由自在に扱う、数少ない真人間ジャグラー。安心感がレベチ。"
team = ""

[[members]]
name = "梶藤"
picture = "kajitou.jpg"
description = "12月に入ったばかりの初心者ボーラー。レアキャラです。"
team = ""

[[members]]
name = "金堀"
picture = "kanahori.jpg"
description = "真面目で努力家、○○○経験もある英語ペラペラな二代目皿のお兄さん。"
team = ""

[[members]]
name = "木村"
picture = "kimura.jpg"
description = "意外と毒舌デビラー女神様。いつもニコニコ"
team = ""

[[members]]
name = "立石"
picture = "tateishi.jpg"
description = "お寿司大好きなボーラー兼デビラー。大阪人の血は熱い。"
team = ""

[[members]]
name = "辻"
picture = ""
description = ""
team = "ジャグリングが特技の変態クラバー。声大きいのに優しい。"

[[members]]
name = "坪内"
picture = "tsubouchi.jpg"
description = "人間が大好きな髪の長いシガラー。ぷらきぞはこしか勝たん。"
team = ""

[[members]]
name = "中川"
picture = "nakagawa.jpg"
description = "めちゃくちゃ上手いボーラー。一見まともそうに見えて若干貢ぎ癖あり。ボールは落とさず金は落とす。"
team = ""

[[members]]
name = "原田"
picture = "harada.jpg"
description = "トスジャグリングできないディアボラー。2個しかできないけどディアボロたくさん持ってる。"
team = ""

[[members]]
name = "藤田"
picture = "hujita.jpg"
description = "ダイナミックな技を好む天災ディアボラー。可愛いキャラクターが好み。意外と頭に矢は刺さっていない。"
team = ""

[[members]]
name = "堀田"
picture = "horita.jpg"
description = "散歩とお笑いが好きなボーラー。お散歩メンバー募集中です！"
team = ""

[[members]]
name = "宮脇"
picture = "miyawaki.jpg"
description = "体操もできるシガラー兼ディアボラー。冬空の下でも素足にサンダルを履くナリ。"
team = ""

[[members]]
name = "向川"
picture = ""
description = "イントロクイズ最強のシガーボクサー🥊めっちゃおもろい"
team = ""

[[members]]
name = "米岡"
picture = ""
description = "東北出身のエンジョイ勢ボーラー。同郷の人を常に探している。"
team = ""

[[members]]
name = "和才"
picture = "wasai.jpg"
description = "みんなの一周先を駆け抜けるボウラー(ビーンバッグ)。稀に煮込みハンバーグを振る舞う。"
team = ""

[[members]]
name = "鷲尾"
picture = "washio.jpg"
description = "最近一人暮らしを始めた元実家系ボーラー。エイトリンガーに転身する機会をうかがっている。"
team = ""