year = 2018

month = 5

day = 5

dow = "土"

firstStart = "14:30" # 昼の部の開演時間

firstOpen = "14:00" # 昼の部の開場時間

secondStart = "18:30" # 夜の部の開演時間

secondOpen = "18:00" # 夜の部の開場時間

showtime = 60

place = "京都教育文化センター"

registerDeadline = "5月4日 (金) 21時"

registerForm = ""


[[casts]]

name = "上野 寛樹"

tool = "ハット"


[[casts]]

name = "小澤 駿弥"

tool = "デビルスティック"


[[casts]]

name = "小松原 裕"

tool = "クラブ"


[[casts]]

name = "清水 翔太"

tool = "ディアボロ"


[[casts]]

name = "砂原 啓人"

tool = "ディアボロ"


[[casts]]

name = "渡辺 悠里"

tool = "ボール"


[[casts]]

name = "鈴木 凌太"

tool = "キャスト"


[[casts]]

name = "竹花 祥"

tool = "キャスト"


[[staffs]]

name = "田中 篤志"

position = "舞台監督"


[[staffs]]

name = "服部 駿佑"

position = "広報統括"


[[staffs]]

name = "古賀 優太"

position = "受付統括"


[[staffs]]

name = "松巾 拓未"

position = "音響"


[[staffs]]

name = "山崎 琉央"

position = "照明"


[[staffs]]

name = "山下 湧志朗"

position = "撮影"


[[staffs]]

name = "小林 悠太"

position = "広報"


[[staffs]]

name = "石水 泰樹"

position = "チケット"


[[staffs]]

name = "稲葉 昂希"

position = "会計/スポンサー"


[[staffs]]

name = "山下 巧 "

position = "大道具"


[[staffs]]

name = "戸板 治紀"

position = "宣伝美術"


[[staffs]]

name = "酒徳 波和"

position = "宣伝美術"


[[staffs]]

name = "戸塚 大貴"

position = "ヘアメイク"



[[staffs]]

name = "白井夢月"

position = "メイク統括"


[[staffs]]

name = "田中嵩士"

position = "ウェブ"


[[prices]]

target = "一般"

price = "1000円"


[[prices]]

target = "大学新入生・高校生以下"

price = "500円"
