year = 2020

month = 5

day1 = 5

dow1 = "火"

firstStart = "14:30" # 昼の部の開演時間

firstOpen = "14:00" # 昼の部の開場時間

secondStart = "18:30" # 夜の部の開演時間

secondOpen = "18:00" # 夜の部の開場時間

showtime = 75

place = "京都教育文化センター"

registerDeadline = "5月4日 (月) 21時"

registerForm = "https://docs.google.com/forms/d/1t9YrlD1ag9GjHB0p-COtwJWLV5F3pC7nBpbL_F_HpOo/edit?usp=drive_web"



[[casts]]

name = "川井　悠生"

tool = "ポイ"



[[casts]]

name = "鈴木　さら"

tool = "ボール"



[[casts]]

name = "田﨑　晃司"

tool = "ディアボロ"



[[casts]]

name = "原田　優真"

tool = "？？？"



[[casts]]

name = "比嘉　魁人"

tool = "ボール"



[[casts]]

name = "宮里　航司"

tool = "デビルスティック"



[[casts]]

name = "吉村　比呂"

tool = "シェーカーカップ"



[[casts]]

name = "吉村　萌杏"

tool = "ディアボロ"



[[casts]]

name = "古城　幸奈"

tool = "キャスト"




[[staffs]] 
  
name = "松巾　拓未" 
  
position = "舞台監督" 
  
  
  
[[staffs]] 
  
name = "小松原　裕" 
  
position = "舞台監督補佐" 
 
 
 
[[staffs]] 
  
name = "比嘉　魁人" 
  
position = "大道具統括" 
  
  
  
[[staffs]] 
  
name = "吉村　比呂" 
  
position = "照明統括" 
 
  
   
[[staffs]] 
  
name = "戸板　治紀" 
  
position = "広報統括" 
  
  
  
[[staffs]] 
  
name = "吉村　萌杏" 
  
position = "宣伝美術統括" 
  
  
  
[[staffs]] 
  
name = "糟谷　悠" 
  
position = "宣伝美術補佐" 
  
  
  
[[staffs]] 
  
name = "砂原　啓人" 
  
position = "受付統括" 
  
  
  
[[staffs]] 
  
name = "古城　幸奈" 
  
position = "メイク統括" 
  
  
  
[[staffs]] 
  
name = "田﨑　晃司" 
  
position = "ヘアメイク統括" 



[[staffs]]

name = "原田　優真"

position = "脚本"
  
  
 
 [[staffs]] 
  
name = "大山　拓海" 
  
position = "大道具" 
  
  
  
[[staffs]] 
  
name = "丸尾　亮太" 
  
position = "大道具" 
 
 
 
[[staffs]] 
  
name = "竹田　瑞萌" 
  
position = "音響" 
  
  
  
[[staffs]] 
  
name = "石川　碧人" 
  
position = "照明" 
  
  
  
[[staffs]] 
  
name = "坂田　寛知" 
  
position = "撮影" 
  
  
  
[[staffs]] 
  
name = "米澤　璃穂" 
  
position = "撮影" 
  
 
 
[[staffs]]

name = "田島　玄基"

position = "広報"
  
  
 
[[staffs]] 
  
name = "榊原　美諸里" 
  
position = "ウェブ"



[[staffs]]

name = "渡邊　優大"

position = "映像"


[[staffs]]

name = "澤近　優真"

position = "会計・スポンサー"
 

  
[[staffs]] 
  
name = "相庭　将行" 
  
position = "宣伝美術" 
  
 
 
[[staffs]] 
 
name = "向後　拓真"

position = "チケット"
  
 
  
[[staffs]] 
  
name = "佐藤　翔太郎" 
  
position = "メイク" 
  
  
  
[[staffs]] 
  
name = "山戸　瞭雅" 
  
position = "ヘアメイク" 



[[prices]]

target = "一般"

price = "1500円"



[[prices]]

target = "大学生"

price = "1000円"



[[prices]]

target = "高校生以下"

price = "500円"

