
#この年はインターネット上での公開を行い、
#例年のと比べていろいろと減っています。
#コピペするときは以前までのをお使いください。


year = 2022

month = 4

day1 = 0

dow1 = "xxx"


place = "後日公開"



[[casts]]

name = "酒徳　波和"

tool = "リング"



[[casts]]

name = "中村　伊吹"

tool = "ポイ"



[[casts]]

name = "中村　拓也"

tool = "ディアボロ"



[[casts]]

name = "山崎　創史"

tool = "ディアボロ"



[[casts]]

name = "山下　巧"

tool = "クリスタル"


[[casts]]

name = "戸板　治紀"

tool = "キャスト"
  
