
year = 2022

month = 4

day1 = 0

dow1 = "xxx"

#firstStart = "xx" # 昼の部の開演時間

#firstOpen = "xx" # 昼の部の開場時間

#secondStart = "xx" # 夜の部の開演時間

#secondOpen = "xx" # 夜の部の開場時間

showtime = 0

place = "後日公開"

registerDeadline = "xx"

registerForm = "xx"



[[casts]]

name = "酒徳 波和"

tool = "リング"



[[casts]]

name = "中村　伊吹"

tool = "ポイ"



[[casts]]

name = "中村　拓也"

tool = "ディアボロ"



[[casts]]

name = "山崎　創史"

tool = "ディアボロ"



[[casts]]

name = "山下　巧"

tool = "クリスタル"


[[casts]]

name = "戸坂　治紀"

tool = "キャスト"

  
[[staffs]] 
  
name = "" 
  
position = "チケット" 
  
  
  
[[staffs]]

name = "澤近　優真"

position = "広報"
  
[[staffs]] 
  
name = "本田　健吾" 
  
position = "照明" 
  
  
  
 
[[staffs]] 
  
name = "藤原　秀慈" 
  
position = "ウェブ"



[[staffs]]

name = "松木　梨南・中井　竜太郎"

position = "映像"


[[staffs]]

name = ""

position = "会計・スポンサー"
 

  
[[staffs]] 
  
name = "松木　梨南" 
  
position = "宣伝美術" 
  
  
[[staffs]] 
  
name = "出井　ななか" 
  
position = "メイク" 
  
  
  
[[staffs]] 
  
name = "" 
  
position = "ヘアメイク" 



[[prices]]

target = "基本無料です。"

price = ""
