
year = 2022

month = 00

day1 = 00

dow1 = ""

firstStart = "" # 昼の部の開演時間

firstOpen = "" # 昼の部の開場時間

secondStart = "" # 夜の部の開演時間

secondOpen = "" # 夜の部の開場時間

showtime = 

place = "京都教育文化センター"

registerDeadline = "5月4日 (月) 21時"

registerForm = ""



[[casts]]

name = "酒徳 波和"

tool = "リング"



[[casts]]

name = "中村　伊吹"

tool = "ポイ"



[[casts]]

name = "中村　拓也"

tool = "ディアボロ"



[[casts]]

name = "山崎　創史"

tool = "ディアボロ"



[[casts]]

name = "山下　巧"

tool = "クリスタル"



[[casts]]

name = "宮里　航司"

tool = "デビルスティック"



[[casts]]

name = "戸坂　治紀"

tool = "キャスト"



[[casts]]

name = "吉村　萌杏"

tool = "ディアボロ"



[[casts]]

name = "古城　幸奈"

tool = "キャスト"




[[staffs]] 
  
name = "" 
  
position = "" 
  
  
  
[[staffs]] 
  
name = "" 
  
position = "" 
 
 
 
[[staffs]] 
  
name = "" 
  
position = "" 
  
  
  
[[staffs]] 
  
name = "" 
  
position = "" 
 
  
   
[[staffs]] 
  
name = "" 
  
position = "" 
  
  
  
[[staffs]] 
  
name = "" 
  
position = "" 
  
  
  
[[staffs]] 
  
name = "" 
  
position = "" 
  
  
  
[[staffs]] 
  
name = "" 
  
position = "" 
  
  
  
[[staffs]] 
  
name = "" 
  
position = "" 
  
  
  
[[staffs]] 
  
name = "" 
  
position = "" 



[[staffs]]

name = ""

position = ""
  
  
 
 [[staffs]] 
  
name = "" 
  
position = "" 
  
  
  
[[staffs]] 
  
name = "" 
  
position = "" 
 
 
 
[[staffs]] 
  
name = "" 
  
position = "" 
  
  
  
[[staffs]] 
  
name = "" 
  
position = "" 
  
  
  
[[staffs]] 
  
name = "" 
  
position = "" 
  
  
  
[[staffs]] 
  
name = "" 
  
position = "" 
  
 
 
[[staffs]]

name = ""

position = "広報"
  
  
 
[[staffs]] 
  
name = "" 
  
position = "ウェブ"



[[staffs]]

name = ""

position = "映像"


[[staffs]]

name = ""

position = "会計・スポンサー"
 

  
[[staffs]] 
  
name = "" 
  
position = "宣伝美術" 
  
 
 
[[staffs]] 
 
name = ""

position = "チケット"
  
 
  
[[staffs]] 
  
name = "" 
  
position = "メイク" 
  
  
  
[[staffs]] 
  
name = "" 
  
position = "ヘアメイク" 



[[prices]]

target = ""

price = ""
