year = 2024
month = 5
date = 6
day = "月・祝"

place = "京都府立文化芸術会館"

[[casts]]
name = "角"
equip = "ボール"
fname = "nodata.jpg"

[[staff]]
name = "中村　伊吹"
roll = "舞台監督"

[[staff]]
name = "酒德　波和"
roll = "舞台監督補佐"

[[staff]]
name = "木村　忠吾"
roll = ""

[[staff]]
name = "藤原　秀慈"
roll = "広報統括"

[[staff]]
name = "角　倫彩子"
roll = "広報補佐・音響"

[[staff]]
name = "遠藤　海人"
roll = "Web"

[[staff]]
name = "須崎　朝香"
roll = "宣伝美術"

[[staff]]
name = "水野　凌斗"
roll = "照明"

[[staff]]
name = "鶴見　高輝"
roll = "大道具統括"

[[staff]]
name = "池田　和陽"
roll = "大道具実働"

[[staff]]
name = "清住　尚平"
roll = ""

[[staff]]
name = "岩田　訓昂"
roll = "メイク"

[[staff]]
name = "永井　伶"
roll = ""

[[staff]]
name = "天野　寛大"
roll = ""

[[staff]]
name = "山田　明"
roll = ""

[[staff]]
name = "平田　大智"
roll = "ヘアメイク"

[[staff]]
name = "佐藤　暢"
roll = "カメラ"

[[staff]]
name = "森本　駿之介"
roll = ""

[[staff]]
name = "中井　竜太郎"
roll = "会計・スポンサー"

[[staff]]
name = "山下　巧"
roll = "受付統括"

[[staff]]
name = "尾鍋　正剛"
roll = "受付"
