year = 2025
month = 5
date = 6
day = "月・祝"

sponsors = [
  "ここにスポンサー名を入力",
  "複数の場合はカンマ区切り",
  "ダブルクォーテーションで囲うのを忘れるとエラーが出ます",
  "全角半角の区別にも注意してください。",
]

promo_url = "https://www.youtube-nocookie.com/embed/DiTXAGlK7dg?si=669YSYkyRKedyx8v"
ofuse_url = "https://ofuse.me/80c44794"
ticket_url = "https://passmarket.yahoo.co.jp/event/show/detail/02bi9qmr8gj31.html"

# 日付型を使いたかったがパース時にエラーが出るため文字列を使用。
latest_update = "2025年1月15日"

[[casts]]
  name = "池田和陽"
  equip = "デビルスティック"
  fname = "ikeda.jpg"

[[casts]]
  name = "遠藤海人"
  equip = "シェイカーカップ"
  fname = "endo.jpg"

[[casts]]
  name = "⻆倫彩子"
  equip = "ボール"
  fname = "sumi.jpg"

[[casts]]
  name = "永井伶"
  equip = "リング"
  fname = "nagai.jpg"

[[casts]]
  name = "水野凌斗"
  equip = "シガーボックス"
  fname = "mizuno.jpg"

[[casts]]
  name = "森本駿之介"
  equip = "ディアボロ"
  fname = "morimoto.jpg"

[[casts]]
  name = "山田明"
  equip = "ディアボロ"
  fname = "yamada.jpg"

[[staff]]
  name = "松木梨南"
  roll = "舞台監督"

[[staff]]
  name = "加藤悠太"
  roll = "舞台監督補佐"

[[staff]]
  name = "中村拓也"
  roll = "舞台監督補佐"

[[staff]]
  name = "尾鍋正剛"
  roll = "広報統括"

[[staff]]
  name = "柴田光之進"
  roll = "広報補佐"

[[staff]]
  name = "佐藤暢"
  roll = "宣伝美術"

[[staff]]
  name = "遠藤海人"
  roll = "Web"

[[staff]]
  name = "永井彾"
  roll = "脚本"

[[staff]]
  name = "水野凌斗"
  roll = "照明統括"

[[staff]]
  name = "藤井瑛士"
  roll = "照明"

[[staff]]
  name = "角倫彩子"
  roll = "音響統括"

[[staff]]
  name = "土井洸史朗"
  roll = "音響"

[[staff]]
  name = "池田和陽"
  roll = "大道具統括"

[[staff]]
  name = "山田明"
  roll = "メイク統括"

[[staff]]
  name = "平田大智"
  roll = "ヘアメイク"

[[staff]]
  name = "坂上優太"
  roll = "カメラ撮影"

[[staff]]
  name = "中川武蔵"
  roll = "カメラ撮影"

[[staff]]
  name = "森本駿之介"
  roll = "会計"

[[staff]]
  name = "岩田訓昂"
  roll = "新歓"

[[staff]]
  name = "船岡美玖"
  roll = "新歓"

[[staff]]
  name = "平田大智"
  roll = "スポンサー"

[[staff]]
  name = "中井竜太郎"
  roll = "受付統括"

[[staff]]
  name = "柴田光之進"
  roll = "受付"

[[staff]]
  name = "水野凌斗"
  roll = "全体演目"
