# JDL当日の日付を入力
year = 2025
month = 5
date = 6
day = "月・祝"

# それぞれ、PV(Youtube), OFUSE, チケットサイトのurlを入力。
# ただし、youtubeは埋め込みのためのurlを取得する必要があります。
promo_url = "https://www.youtube-nocookie.com/embed/xxxx"
ofuse_url = "https://ofuse.me/xxxx"
ticket_url = "https://passmarket.yahoo.co.jp/event/show/detail/xxxx.html"

# 最終更新日を入力
# 日付型を使いたかったがパース時にエラーが出るため文字列を使用。
latest_update = "2025年1月15日"

# 広報統括の名前を入力
pr_manager = "テスト　広報担当"

# 角括弧 [] の中にスポンサーをカンマ区切りで入力してください。
# 例：
# sponsors = [
#   "スポンサーA",
#   "スポンサーB",
#   "スポンサーC",
# ]
sponsors = []

# 演者の名前、道具、写真のファイル名を入力。
# 例年五十音順に並べている。
# 写真はimg/jdl{開催年}に保存。
# スタッフも同様。
[[casts]]
  name = "演者１"
  equip = "デビルスティック"
  fname = "ikeda.jpg"

[[casts]]
  name = "演者１"
  equip = "ディアボロ"
  fname = "yamada.jpg"

# スタッフ
[[staff]]
  name = "テスト　舞台監督"
  roll = "舞台監督"

[[staff]]
  name = "テスト　舞台監督補佐"
  roll = "舞台監督補佐"

[[staff]]
  name = "名前"
  roll = "舞台監督"
