name: github_pages

on:
  push:
    branches:
      - dev

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: "23.x"
      - run: node --version
      - run: npm --version

      - name: Install libs
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: master
          cname: juggling-donuts.org
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
